rules:
  indentation:
    - 0
  mixins-before-declarations:
    - 1
    -
      exclude: ['composes']
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-misspelled-properties:
    - 1
    -
      extra-properties:
        - composes
  property-sort-order:
  - 1
  -
    order: concentric
    ignore-custom-properties: true
  single-line-per-selector:
    - 0
